### ISSUE TITLE
Add support for Web Identity authentication to AWS

### ISSUE THREAD

**Issue by rkujawa** [mlabouardy/komiser#208]
**Is your feature request related to a problem? Please describe.**
When running in a Kubernetes environment on AWS, it is not safe or even necessary to use secret and access key to gain access to AWS API. It is much better to use Web Identity authentication - this allows the application running on Kubernetes in AWS, to access the AWS API without the need to use static credentials that could be easily stolen. Instead, a token is used that is automatically injected into the Pod by the Kubernetes, using this token, the application can obtain a particular IAM role.

This feature is sometimes also called "fine-grained IAM roles for service accounts".

**Describe the solution you'd like**
Support for Web Identity authentication to be added in Komiser. As far as I am aware, this feature is already supported by AWS Go SDK.

**Describe alternatives you've considered**
A workaround is to use authentication using hard-coded access and secret key, like in example currently available in deployment subdirectory. However, it is a security risk that I would prefer not to take.

**Additional context**
See AWS documentation:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
https://aws.github.io/aws-eks-best-practices/security/docs/iam/#iam-roles-for-service-accounts-irsa
https://aws.amazon.com/blogs/containers/diving-into-iam-roles-for-service-accounts/

**Comment by mlabouardy** [comment]
@rkujawa I've updated the official Helm Chart with instructions on how to use IRSA :)
https://github.com/komiserio/helm

**Comment by rkujawa** [comment]
@mlabouardy Wow so quick 👍. Thank you, will test as soon as possible.

**Comment by rkujawa** [comment]
@mlabouardy I've managed to deploy Komiser to my AWS EKS cluster, sadly there's still some problem that may be related to authentication.

I web UI I get a lot of errors like `someService:someFunction is missing`.

However, the log for Komiser pod does not contain any useful information that would help pinpointing where's exactly the problem. Sometimes a message appears:
```
before assume role
after assume role
```
Other than messages above, it's just HTTP access logs:
```
2022/07/27 10:27:57 Using in-memory cache
127.0.0.1 - - [27/Jul/2022:10:28:33 +0000] "GET / HTTP/1.1" 200 22504
127.0.0.1 - - [27/Jul/2022:10:28:35 +0000] "GET /runtime.70b7f973647a1732.js HTTP/1.1" 200 1166
127.0.0.1 - - [27/Jul/2022:10:28:35 +0000] "GET /styles.ecfcf3f49b831a63.css HTTP/1.1" 200 520
127.0.0.1 - - [27/Jul/2022:10:28:35 +0000] "GET /polyfills.b6aa372f871f03e7.js HTTP/1.1" 200 68350
127.0.0.1 - - [27/Jul/2022:10:28:35 +0000] "GET /scripts.a501a6ecda8e8691.js HTTP/1.1" 200 680858
127.0.0.1 - - [27/Jul/2022:10:28:35 +0000] "GET /main.acd47005defc6f75.js HTTP/1.1" 200 2285216
127.0.0.1 - - [27/Jul/2022:10:28:37 +0000] "GET /aws/profiles HTTP/1.1" 200 2
127.0.0.1 - - [27/Jul/2022:10:28:37 +0000] "GET /integrations HTTP/1.1" 200 15
before assume role
after assume role
127.0.0.1 - - [27/Jul/2022:10:28:37 +0000] "GET /aws/ec2/regions HTTP/1.1" 500 44
127.0.0.1 - - [27/Jul/2022:10:28:37 +0000] "GET /aws/resources/regions HTTP/1.1" 500 39
127.0.0.1 - - [27/Jul/2022:10:28:37 +0000] "GET /aws/cost/history HTTP/1.1" 500 41
```

I didn't use your helm chart, since resources required some modifications to run on my environment. However, I don't think this is related. Just for reference my resources currently look like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komiser
spec:
  selector:
    matchLabels:
      app: komiser
  template:
    metadata:
      name: komiser
      labels:
        app: komiser
    spec:
      serviceAccountName: komiser
      containers:
        - name: komiser
          image: mlabouardy/komiser:2.8.1
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
---
apiVersion: v1
kind: Service
metadata:
  name: komiser
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
  selector:
    app: komiser
apiVersion: v1
kind: ServiceAccount
metadata:
  name: komiser
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::139536746838:role/Komiser-prod1
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./komiser-deployment.yaml
  - ./komiser-service.yaml
  - ./komiser-serviceaccount.yaml
```

I am certain that Web Identity authentication is working correctly, since I managed to get into the Pod and check it with AWS CLI:
```
rkujawa-laptop:komiser (release/prod1) $ kubectl -n komiser exec -it komiser-5b4785f5c4-czj6f -- /bin/sh
/ # apk add aws-cli
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/27) Installing libbz2 (1.0.8-r1)
(2/27) Installing expat (2.4.7-r0)
(3/27) Installing libffi (3.4.2-r1)
(4/27) Installing gdbm (1.22-r0)
(5/27) Installing xz-libs (5.2.5-r1)
(6/27) Installing libgcc (10.3.1_git20211027-r0)
(7/27) Installing libstdc++ (10.3.1_git20211027-r0)
(8/27) Installing mpdecimal (2.5.1-r1)
(9/27) Installing ncurses-terminfo-base (6.3_p20211120-r1)
(10/27) Installing ncurses-libs (6.3_p20211120-r1)
(11/27) Installing readline (8.1.1-r0)
(12/27) Installing sqlite-libs (3.36.0-r0)
(13/27) Installing python3 (3.9.13-r1)
(14/27) Installing groff (1.22.4-r1)
(15/27) Installing py3-six (1.16.0-r0)
(16/27) Installing py3-dateutil (2.8.2-r0)
(17/27) Installing py3-docutils (0.16-r3)
(18/27) Installing py3-jmespath (0.10.0-r1)
(19/27) Installing py3-urllib3 (1.26.7-r0)
(20/27) Installing py3-botocore (1.21.49-r0)
(21/27) Installing py3-s3transfer (0.5.0-r0)
(22/27) Installing py3-colorama (0.4.4-r1)
(23/27) Installing yaml (0.2.5-r0)
(24/27) Installing py3-yaml (5.4.1.1-r1)
(25/27) Installing py3-asn1 (0.4.8-r1)
(26/27) Installing py3-rsa (4.7.2-r0)
(27/27) Installing aws-cli (1.19.105-r0)
Executing busybox-1.34.1-r7.trigger
OK: 141 MiB in 46 packages
/ # aws sts get-caller-identity
{
    "UserId": "AROASA7IJZFLG3QMETSFQ:botocore-session-1658917988",
    "Account": "139536746838",
    "Arn": "arn:aws:sts::139536746838:assumed-role/Komiser-prod1/botocore-session-1658917988"
}
/ # env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::139536746838:role/Komiser-prod1
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_DEFAULT_REGION=eu-central-1
/ # aws ec2 describe-instances 
{
    "Reservations": [
        {
            "Groups": [],
            "Instances": [
                {
                    "AmiLaunchIndex": 0,
                    "ImageId": "ami-04cf43aca3e6f3de3",
                    "InstanceId": "i-0a616552ed86b952c",
(...)
```

Please advise how to debug this further.
