### ISSUE TITLE
Spot instance counter always shows 0

### ISSUE THREAD

**Issue by rkujawa** [mlabouardy/komiser#210]
**Describe the bug**
The spot instance counter in compute tab of Komiser web UI always shows 0.

**To Reproduce**
- Open Compute tab in web UI
- See 0 instead of actual number of spot instances

**Expected behavior**
I expect to see the real amount of spot instances.

**Screenshots**
It just shows:
```
Spot Instances
0 
```

There are no related errors in Komiser Pod log.

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: Safari
 - Version: 15.6

**Additional context**
Currently I have 6 spot instances running which I have confirmed with AWS CLI:
```
$ aws ec2 describe-spot-instance-requests | jq '.SpotInstanceRequests[].InstanceId'
"i-01c4a9226ffaa6554"
"i-0be997b5467bbae96"
"i-0325d1c32efbf7d1b"
"i-06b6237f49c5e18d6"
"i-055db654a6cb7c0b6"
"i-0fbf4749d36d35659"
```

**Comment by mlabouardy** [comment]
@rkujawa an IAM permission was missing in the recommended Komiser policy https://github.com/mlabouardy/komiser/commit/06861a8359bec0910ec12efb45e8505b0a008004

**Comment by rkujawa** [comment]
@mlabouardy I've modified my policy as in https://github.com/mlabouardy/komiser/commit/06861a8359bec0910ec12efb45e8505b0a008004 and restarted the komiser Pod using image `mlabouardy/komiser:06861a8359bec0910ec12efb45e8505b0a008004` (built 3h ago), I still see zero spot instances in web UI.

**Comment by mlabouardy** [comment]
let me retry with an EKS managed node groups and get back to you :)

**Comment by rkujawa** [comment]
An example managed node group setup (for [eksctl](https://github.com/weaveworks/eksctl)), for reference:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: linker-k8s-infradev2
  region: eu-central-1
  version: "1.22"
managedNodeGroups:
  - name: mspot-infradev2-arm-1c
    labels: {bottlerocket.aws/updater-interface-version: 2.0.0}
    amiFamily: Bottlerocket
    instanceTypes: ["t4g.medium", "t4g.large"]
    bottlerocket:
      settings:
        kernel:
          sysctl:
            fs.inotify.max_user_watches: "262143"
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    maxPodsPerNode: 110
    volumeSize: 100
    spot: true
    privateNetworking: true
    subnets:
      - eu-central-1c
    ssh:
      allow: true
      publicKeyPath: ssh_nodes
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      withAddonPolicies:
        externalDNS: true
        albIngress: true
        certManager: true
        autoScaler: true
```
